DROP SEQUENCE S_IDENTITY;

ALTER TABLE T_IDENTITY DROP PRIMARY KEY CASCADE;
DROP TABLE T_IDENTITY CASCADE CONSTRAINTS;

DROP TABLE T_IDENTITY_TO_IDENTITY CASCADE CONSTRAINTS;

DROP TABLE T_IDENTITY_TO_ROLE CASCADE CONSTRAINTS;

ALTER TABLE T_IDENTITY_TYPE DROP PRIMARY KEY CASCADE;
DROP TABLE T_IDENTITY_TYPE CASCADE CONSTRAINTS;


ALTER TABLE T_RIGHT DROP PRIMARY KEY CASCADE;
DROP TABLE T_RIGHT CASCADE CONSTRAINTS;


ALTER TABLE T_ROLE DROP PRIMARY KEY CASCADE;
DROP TABLE T_ROLE CASCADE CONSTRAINTS;

DROP TABLE T_ROLE_TO_RIGHT CASCADE CONSTRAINTS;

SHOW ERRORS;

exit
