
ALTER TABLE T_IDENTITY ADD (
  PRIMARY KEY (IDENTITY_KEY),
  UNIQUE (IDENTITY_NAME));

ALTER TABLE T_IDENTITY_TO_IDENTITY ADD (
  CONSTRAINT U_ID_TO_ID UNIQUE (PARENT_IDENTITY_KEY, IDENTITY_KEY));

ALTER TABLE T_IDENTITY_TO_ROLE ADD (
  UNIQUE (ROLE_KEY, IDENTITY_KEY));

ALTER TABLE T_IDENTITY_TYPE ADD (
  PRIMARY KEY (IDENTITY_TYPE_KEY),
  UNIQUE (IDENTITY_TYPE_NAME));

ALTER TABLE T_RIGHT ADD (
  PRIMARY KEY (RIGHT_KEY),
  UNIQUE (RIGHT_NAME));

ALTER TABLE T_ROLE ADD (
  PRIMARY KEY (ROLE_KEY),
  UNIQUE (ROLE_NAME));

ALTER TABLE T_ROLE_TO_RIGHT ADD (
  UNIQUE (ROLE_KEY, RIGHT_KEY));

ALTER TABLE T_IDENTITY ADD (
  FOREIGN KEY (OPERATOR_MODIFIED) 
    REFERENCES T_IDENTITY (IDENTITY_KEY),
  FOREIGN KEY (IDENTITY_TYPE_KEY) 
    REFERENCES T_IDENTITY_TYPE (IDENTITY_TYPE_KEY));

ALTER TABLE T_IDENTITY_TO_IDENTITY ADD (
  FOREIGN KEY (IDENTITY_KEY) 
    REFERENCES T_IDENTITY (IDENTITY_KEY),
  FOREIGN KEY (PARENT_IDENTITY_KEY) 
    REFERENCES T_IDENTITY (IDENTITY_KEY),
  FOREIGN KEY (OPERATOR_MODIFIED) 
    REFERENCES T_IDENTITY (IDENTITY_KEY));

ALTER TABLE T_IDENTITY_TO_ROLE ADD (
  FOREIGN KEY (OPERATOR_MODIFIED) 
    REFERENCES T_IDENTITY (IDENTITY_KEY),
  FOREIGN KEY (ROLE_KEY) 
    REFERENCES T_ROLE (ROLE_KEY),
  FOREIGN KEY (IDENTITY_KEY) 
    REFERENCES T_IDENTITY (IDENTITY_KEY));

ALTER TABLE T_IDENTITY_TYPE ADD (
  FOREIGN KEY (OPERATOR_MODIFIED) 
    REFERENCES T_IDENTITY (IDENTITY_KEY));

ALTER TABLE T_RIGHT ADD (
  FOREIGN KEY (OPERATOR_MODIFIED) 
    REFERENCES T_IDENTITY (IDENTITY_KEY));

ALTER TABLE T_ROLE ADD (
  FOREIGN KEY (OPERATOR_MODIFIED) 
    REFERENCES T_IDENTITY (IDENTITY_KEY));

ALTER TABLE T_ROLE_TO_RIGHT ADD (
  FOREIGN KEY (OPERATOR_MODIFIED) 
    REFERENCES T_IDENTITY (IDENTITY_KEY),
  FOREIGN KEY (ROLE_KEY) 
    REFERENCES T_ROLE (ROLE_KEY),
  FOREIGN KEY (RIGHT_KEY) 
    REFERENCES T_RIGHT (RIGHT_KEY));


exit
