DROP VIEW IF EXISTS V_IDENTITY_TO_RIGHT ;

DROP VIEW IF EXISTS V_IDENTITY ;

DROP VIEW IF EXISTS V_IDENTITY_TO_IDENTITY ;

DROP TABLE IF EXISTS T_IDENTITY_TO_RIGHT CASCADE ;

DROP TABLE IF EXISTS T_RIGHT CASCADE ;

DROP TABLE IF EXISTS T_IDENTITY_TO_IDENTITY CASCADE ;

DROP TABLE IF EXISTS T_IDENTITY CASCADE ;

DROP TABLE IF EXISTS T_IDENTITY_TYPE CASCADE ;

DROP TRIGGER IF EXISTS TR_T_IDENTITY_LM ON T_IDENTITY CASCADE ;

DROP TRIGGER IF EXISTS TR_T_IDENTITY_TO_IDENTITY_LM ON T_IDENTITY_TO_IDENTITY CASCADE ;

DROP TRIGGER IF EXISTS TR_T_IDENTITY_TO_RIGHT_LM ON T_IDENTITY_TO_RIGHT CASCADE ;

DROP TRIGGER IF EXISTS TR_T_IDENTITY_TYPE_LM ON T_IDENTITY_TYPE CASCADE ;

DROP TRIGGER IF EXISTS TR_T_RIGHT_LM ON T_RIGHT CASCADE ;

drop function IF EXISTS f_last_modified() cascade ;

commit ;