CREATE OR REPLACE VIEW V_IDENTITY_TO_IDENTITY
(IDENTITY_KEY, PARENT_IDENTITY_KEY, PARENT_IDENTITY_NAME, ENABLED, LOGIN_ENABLED, 
 END_DATE, IDENTITY_TYPE_KEY, IDENTITY_TYPE_NAME)
AS 
SELECT 
  a.IDENTITY_KEY 
, PARENT_IDENTITY_KEY 
, b.IDENTITY_NAME 
, b.ENABLED 
, b.LOGIN_ENABLED 
, b.END_DATE 
, c.IDENTITY_TYPE_KEY 
, c.IDENTITY_TYPE_NAME 
from T_IDENTITY_TO_IDENTITY a, T_IDENTITY b, T_IDENTITY_TYPE c 
where a.PARENT_IDENTITY_KEY=b.IDENTITY_KEY and b.IDENTITY_TYPE_KEY=c.IDENTITY_TYPE_KEY;


CREATE VIEW V_IDENTITY_TO_RIGHT
AS 
SELECT 
  B.IDENTITY_KEY 
, B.IDENTITY_NAME 
, C.RIGHT_KEY 
, C.RIGHT_NAME 
, A.RIGHT_VALUE 
, A.RIGHT_CONTEXT 
, A.LAST_MODIFIED 
FROM T_IDENTITY_TO_RIGHT A, T_IDENTITY B, T_RIGHT C 
WHERE A.IDENTITY_KEY = B.IDENTITY_KEY 
AND A.RIGHT_KEY = C.RIGHT_KEY;

CREATE OR REPLACE VIEW V_IDENTITY
(IDENTITY_NAME, IDENTITY_KEY, FIRST_NAME, LAST_NAME, EMAIL, 
 IDENTITY_TYPE_KEY, IDENTITY_TYPE_NAME, DESCRIPTION, PARENT_IDENTITY_KEY, PARENT_IDENTITY_NAME, 
 ENABLED, START_DATE, END_DATE, LAST_MODIFIED, OPERATOR_MODIFIED, 
 FULL_NAME, LOGIN_ENABLED, PHONE, EMAIL2,EXTERNAL_KEY,EXTERNAL_ID)
AS 
SELECT 
  a.identity_name 
, a.identity_key 
, a.first_name 
, a.last_name 
, a.email 
, a.IDENTITY_TYPE_KEY 
, c.IDENTITY_TYPE_NAME 
, a.DESCRIPTION 
, b.PARENT_IDENTITY_KEY 
, b.PARENT_IDENTITY_NAME 
, a.ENABLED 
, a.START_DATE 
, a.END_DATE 
, a.LAST_MODIFIED 
, a.OPERATOR_MODIFIED 
, a.LAST_NAME || ', ' || a.FIRST_NAME 
, a.LOGIN_ENABLED 
, a.PHONE 
, a.email2 
, a.EXTERNAL_KEY
, a.EXTERNAL_ID
 from t_identity a, v_identity_to_identity b, t_identity_type c 
where a.IDENTITY_KEY=b.IDENTITY_KEY and a.IDENTITY_TYPE_KEY=c.IDENTITY_TYPE_KEY;

