DROP VIEW IF EXISTS V_IDENTITY_TO_RIGHT ;

DROP VIEW IF EXISTS V_IDENTITY ;

DROP VIEW IF EXISTS V_IDENTITY_TO_IDENTITY ;

DROP TABLE IF EXISTS T_IDENTITY_TO_IDENTITY ;
DROP TABLE IF EXISTS T_IDENTITY_TO_RIGHT ;
DROP TABLE IF EXISTS T_IDENTITY ;
DROP TABLE IF EXISTS T_IDENTITY_TYPE ;
DROP TABLE IF EXISTS T_RIGHT ;

